### ISSUE TITLE
Can't build package is installed from Github

### ISSUE THREAD

**Issue by dks17** [neroniaky/angular2-token#434]
```console
node --version
v10.0.0
npm --version
6.0.1
nvm --version
0.33.11

npm run build

> angular2-token@0.2.0-beta.14 build /home/user/node_modules/angular2-token
> rimraf dist && ng-packagr -p ng-package.json

Building Angular Package
Building entry point 'angular2-token'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15

BUILD ERROR
Could not resolve './a2t-ui/a2t-ui.module' from .ng_pkg_build/angular2-token/out/public_api.js
Error: Could not resolve './a2t-ui/a2t-ui.module' from .ng_pkg_build/angular2-token/out/public_api.js
    at error (/home/user/node_modules/angular2-token/node_modules/rollup/dist/rollup.js:170:15)
    at /home/user/node_modules/angular2-token/node_modules/rollup/dist/rollup.js:19580:25
```

**Comment by neroniaky** [comment]
Could you try again? Should be fixed by now.
