### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by niloyc** [neroniaky/angular2-token#79]
I get a long list of errors as shown at the end. I am not exactly sure what is wrong since all the files it says it cannot find exists inside the "node_modules" folder.

All I have done is ,

`npm install`

and then add `Angular2TokenService` provider in `app.module.ts` as per the instruction page.

No other changes were made to the project.

I am using,
angular2-token: 0.2.0-beta.4
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: linux x64

```
ERROR in ./~/angular2-token/src/a2t-ui/a2t-sign-in/a2t-sign-in.component.ts
Module not found: Error: Can't resolve 'a2t-sign-in.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-sign-in'
 @ ./~/angular2-token/src/a2t-ui/a2t-sign-in/a2t-sign-in.component.ts 36:22-59
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-sign-up/a2t-sign-up.component.ts
Module not found: Error: Can't resolve 'a2t-sign-up.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-sign-up'
 @ ./~/angular2-token/src/a2t-ui/a2t-sign-up/a2t-sign-up.component.ts 36:22-59
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-reset-password/a2t-reset-password.component.ts
Module not found: Error: Can't resolve 'a2t-reset-password.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-reset-password'
 @ ./~/angular2-token/src/a2t-ui/a2t-reset-password/a2t-reset-password.component.ts 32:22-66
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-reset-password/a2t-reset-password.component.ts
Module not found: Error: Can't resolve 'a2t-reset-password.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-reset-password'
 @ ./~/angular2-token/src/a2t-ui/a2t-reset-password/a2t-reset-password.component.ts 33:21-64
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-update-password/a2t-update-password.component.ts
Module not found: Error: Can't resolve 'a2t-update-password.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-update-password'
 @ ./~/angular2-token/src/a2t-ui/a2t-update-password/a2t-update-password.component.ts 34:22-67
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-ui.routes.ts
Module build failed: Error: /home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-ui.routes.ts (25,14): Exported variable 'a2tRoutes' has or is using name 'ModuleWithProviders' from external module "/home/niloy/workspace/booksquare-web/node_modules/@angular/core/src/metadata/ng_module" but cannot be named.)
    at _checkDiagnostics (/home/niloy/workspace/booksquare-web/node_modules/@ngtools/webpack/src/loader.js:115:15)
    at /home/niloy/workspace/booksquare-web/node_modules/@ngtools/webpack/src/loader.js:140:17
 @ ./~/angular2-token/src/a2t-ui/index.ts 4:0-32
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-ui.component.ts
Module not found: Error: Can't resolve 'a2t-ui.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui'
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.component.ts 17:22-54
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-ui.component.ts
Module not found: Error: Can't resolve 'a2t-ui.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui'
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.component.ts 18:21-52
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-links/a2t-links.component.ts
Module not found: Error: Can't resolve 'a2t-links.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-links'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-links/a2t-links.component.ts 21:22-57
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-links/a2t-links.component.ts
Module not found: Error: Can't resolve 'a2t-links.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-links'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-links/a2t-links.component.ts 22:21-55
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-error/a2t-error.component.ts
Module not found: Error: Can't resolve 'a2t-error.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-error'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-error/a2t-error.component.ts 22:21-55
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-headline/a2t-headline.component.ts
Module not found: Error: Can't resolve 'a2t-headline.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-headline'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-headline/a2t-headline.component.ts 18:21-58
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form.component.ts
Module not found: Error: Can't resolve 'a2t-form.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-form'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form.component.ts 19:22-56
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form.component.ts
Module not found: Error: Can't resolve 'a2t-form.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-form'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form.component.ts 20:21-54
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field/a2t-form-field.component.ts
Module not found: Error: Can't resolve 'a2t-form-field.component.html' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field/a2t-form-field.component.ts 37:22-62
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field/a2t-form-field.component.ts
Module not found: Error: Can't resolve 'a2t-form-field.component.css' in '/home/niloy/workspace/booksquare-web/node_modules/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field'
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/a2t-form-field/a2t-form-field.component.ts 38:21-60
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-form/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/a2t-shared.module.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-shared/index.ts
 @ ./~/angular2-token/src/a2t-ui/index.ts
 @ ./~/angular2-token/src/a2t-ui/a2t-ui.module.ts
 @ ./~/angular2-token/angular2-token.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

```

**Comment by bkosik24** [comment]
I actually had the same issue. The workaround that I did to get it working was to go into each of the directories and change it to the relative path of both the templateUrl & stylesUrl. Ex: `templateUrl: 'a2t-form-field.component.html'` to `templateUrl: './a2t-form-field.component.html'`.. I'm thinking it has to do with webpack and how it is loading/requiring all the files but I could be wrong. I'm pretty new to Angular2 so I'm still searching for a better answer.

**Comment by niloyc** [comment]
@bkosik24 Thanks. I followed the changes you made in your forked repo and it compiles fine now. I assume this would still remain an issue due to not working "out of the box".
